### ISSUE TITLE
[BUG] TypeError: azure.identity._credentials.managed_identity.ManagedIdentityCredential() got multiple values for keyword argument 'client_id'

### ISSUE THREAD

**Issue by redranger250** [salt-extensions/saltext-azurerm#46]
**Description**
Using azurerm_keyvault_vault.present throws error stating multiple values for client_id are found, even though only one has been defined.

TypeError: azure.identity._credentials.managed_identity.ManagedIdentityCredential() got multiple values for keyword argument 'client_id'

**Setup**
State file : 

{% set profile = {"subscription_id" : "xxxxx", "tenant": "xxxxx", "secret": "xxxxx", "client_id": "xxxxx"   } %}
Ensure key vault exists:
    azurerm_keyvault_vault.present:
        - name: SaltStackKeyVault
        - resource_group: xxx
        - location: xxxx
        - tenant_id: xxxxx
        - sku:  Standard
        - connection_auth:  {{ profile }}

Please be as specific as possible and give set-up details.
Source of code base, states/pillars/templates, are in Azure DevOps repository

- [ ] on-prem machine
- [x ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

**Screenshots**

**Versions Report**

sudo salt-minion --versions-report
Salt Version:
            Salt: 3006.6
 
Python Version:
          Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]
 
Dependency Versions:
            cffi: 1.14.6
        cherrypy: 18.6.1
        dateutil: 2.8.1
       docker-py: Not Installed
           gitdb: Not Installed
       gitpython: Not Installed
          Jinja2: 3.1.3
         libgit2: Not Installed
    looseversion: 1.0.2
        M2Crypto: Not Installed
            Mako: Not Installed
         msgpack: 1.0.2
    msgpack-pure: Not Installed
    mysql-python: Not Installed
       packaging: 22.0
       pycparser: 2.21
        pycrypto: Not Installed
    pycryptodome: 3.19.1
          pygit2: Not Installed
    python-gnupg: 0.4.8
          PyYAML: 6.0.1
           PyZMQ: 23.2.0
          relenv: 0.14.2
           smmap: Not Installed
         timelib: 0.2.4
         Tornado: 4.5.3
             ZMQ: 4.3.4
 
Salt Extensions:
 saltext.azurerm: 4.0.1
 
System Versions:
            dist: rhel 9.3 Plow
          locale: utf-8
         machine: x86_64
         release: 5.14.0-362.18.1.el9_3.x86_64
          system: Linux
         version: Red Hat Enterprise Linux 9.3 Plow

/opt/saltstack/salt/bin/pip list
Package                     Version
--------------------------- ---------
adal                        1.2.7
azure-batch                 12.0.0
azure-common                1.1.28
azure-core                  1.24.2
azure-graphrbac             0.61.1
azure-identity              1.15.0
azure-keyvault              4.2.0
azure-keyvault-certificates 4.7.0
azure-keyvault-keys         4.8.0
azure-keyvault-secrets      4.7.0
azure-mgmt-authorization    2.0.0
azure-mgmt-batch            16.2.0
azure-mgmt-compute          27.1.0
azure-mgmt-core             1.3.2
azure-mgmt-dns              8.0.0
azure-mgmt-keyvault         10.1.0
azure-mgmt-monitor          6.0.1
azure-mgmt-msi              6.0.1
azure-mgmt-network          20.0.0
azure-mgmt-privatedns       1.0.0
azure-mgmt-resource         21.1.0
azure-mgmt-storage          21.0.0
azure-mgmt-subscription     3.0.0
azure-mgmt-web              6.1.0
azure-nspkg                 3.0.2
azure-storage-blob          12.12.0
azure-storage-common        2.1.0
azure-storage-file          2.1.0
azure-storage-nspkg         3.1.0
azure-storage-queue         12.3.0
certifi                     2023.7.22
cffi                        1.14.6
charset-normalizer          3.2.0
cheroot                     8.5.2
CherryPy                    18.6.1
contextvars                 2.4
cryptography                41.0.7
distro                      1.5.0
idna                        3.2
immutables                  0.15
importlib-metadata          6.0.0
isodate                     0.6.1
jaraco.classes              3.2.1
jaraco.collections          3.4.0
jaraco.functools            2.0
jaraco.text                 3.5.1
Jinja2                      3.1.3
jmespath                    1.0.1
looseversion                1.0.2
MarkupSafe                  2.1.2
more-itertools              5.0.0
msal                        1.26.0
msal-extensions             1.1.0
msgpack                     1.0.2
msrest                      0.7.1
msrestazure                 0.6.4
oauthlib                    3.2.2
packaging                   22.0
pip                         23.3.2
portalocker                 2.8.2
portend                     2.4
psutil                      5.8.0
pycparser                   2.21
pycryptodomex               3.19.1
PyJWT                       2.8.0
pyOpenSSL                   23.2.0
python-dateutil             2.8.1
python-gnupg                0.4.8
pytz                        2022.1
PyYAML                      6.0.1
pyzmq                       23.2.0
relenv                      0.14.2
requests                    2.31.0
requests-oauthlib           1.3.1
rpm-vercmp                  0.1.2
salt                        3006.6
saltext.azurerm             4.0.1
setproctitle                1.3.2
setuptools                  68.2.2
six                         1.16.0
tempora                     4.1.1
timelib                     0.2.5
typing_extensions           4.9.0
urllib3                     1.26.18
wheel                       0.42.0
zc.lockfile                 1.4
zipp                        3.6.0

</details>

**Additional context**
full error

local:
----------
          ID: Ensure key vault exists
    Function: azurerm_keyvault_vault.present
        Name: SaltStackKeyVault
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/state.py", line 2423, in call
                  ret = self.states[cdata["full"]](
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
                  ret = self.loader.run(run_func, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1293, in wrapper
                  return f(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/saltext/azurerm/states/azurerm_keyvault_vault.py", line 193, in present
                  vault = __salt__["azurerm_keyvault_vault.get"](
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
                  ret = self.loader.run(run_func, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/saltext/azurerm/modules/azurerm_keyvault_vault.py", line 305, in get
                  vconn = saltext.azurerm.utils.azurerm.get_client("keyvault", **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/saltext/azurerm/utils/azurerm.py", line 161, in get_client
                  credentials, subscription_id, cloud_env = _determine_auth(**kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/saltext/azurerm/utils/azurerm.py", line 102, in _determine_auth
                  credentials = DefaultAzureCredential(authority=authority, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/azure/identity/_credentials/default.py", line 163, in __init__
                  ManagedIdentityCredential(
              TypeError: azure.identity._credentials.managed_identity.ManagedIdentityCredential() got multiple values for keyword argument 'client_id'
     Started: 12:03:02.867137
    Duration: 134.389 ms
     Changes:

**Comment by corey-hammerton** [comment]
I get the same TypeError when running the `list_nodes` function. I've confirmed that I have only one `client_id` value defined

```
[ERROR   ] There was an error running the function: azure.identity._credentials.managed_identity.ManagedIdentityCredential() got multiple values for keyword argument 'client_id'
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cloud/cli.py", line 242, in run
    ret = mapper.do_function(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cloud/__init__.py", line 1567, in do_function
    return {alias: {driver: self.clouds[fun](call="function")}}
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/extras-3.10/saltext/azurerm/clouds/azurerm.py", line 466, in list_nodes
    nodes = list_nodes_full()
  File "/opt/saltstack/salt/extras-3.10/saltext/azurerm/clouds/azurerm.py", line 483, in list_nodes_full
    netapi_versions = get_api_versions(
  File "/opt/saltstack/salt/extras-3.10/saltext/azurerm/clouds/azurerm.py", line 186, in get_api_versions
    resconn = get_conn(client_type="resource")
  File "/opt/saltstack/salt/extras-3.10/saltext/azurerm/clouds/azurerm.py", line 260, in get_conn
    client = saltext.azurerm.utils.azurerm.get_client(client_type=client_type, **conn_kwargs)
  File "/opt/saltstack/salt/extras-3.10/saltext/azurerm/utils/azurerm.py", line 161, in get_client
    credentials, subscription_id, cloud_env = _determine_auth(**kwargs)
  File "/opt/saltstack/salt/extras-3.10/saltext/azurerm/utils/azurerm.py", line 102, in _determine_auth
    credentials = DefaultAzureCredential(authority=authority, **kwargs)
  File "/opt/saltstack/salt/extras-3.10/azure/identity/_credentials/default.py", line 126, in __init__
    credentials.append(ManagedIdentityCredential(client_id=managed_identity_client_id, **kwargs))
TypeError: azure.identity._credentials.managed_identity.ManagedIdentityCredential() got multiple values for keyword argument 'client_id'
```
